### ISSUE TITLE
problems adding vhostuser interface to VM 

### ISSUE THREAD

**Issue by ballle98** [chaudron/ovs_perf#30]
Lots of headaches trying to set this up in RHEL7.6

Newer versions of OVS use dpdkvhostuserclient instead of dpdkvhostuser.  Basically it is expecting QEMU to create the socket.

http://docs.openvswitch.org/en/latest/topics/dpdk/vhost-user/

I see the difference in the qemu options, you add "server" to the chardev option but I don't see how to pass this through virt-install

**Comment by chaudron** [comment]
The documentation already uses the dpdkvhostuserclient so all the commands will take care of this mode. 

The ovs side is configured as client, but quemu needs to be server. system \
  --network vhostuser,source_type=unix,source_path=/tmp/vhost-sock0,source_mode=server,model=virtio,driver_queues=2

This documentation was tested with Rhel7.6. For RHEL8 see the rhel8 branch.

**Comment by chaudron** [comment]
Closing due to no update after information was given.
