### ISSUE TITLE
can't figure out where liquidio fw_type comes from

### ISSUE THREAD

**Issue by FlorianHeigl** [chaudron/ovs_perf#36]
Hi,

just a stupid question, you set `modprobe liquidio fw_type=vsw` but
- my system just locks up if i try that
- i cannot find any other reference to this in the whole internets (fair enough)
- i cannot figure where this firmware ought to come from

i can see those:

```
tschike:/usr/bin# ls /lib/firmware/liquidio/
lio_210nv_nic.bin  lio_210sv_nic.bin  lio_23xx_nic.bin  lio_410nv_nic.bin
``` 

with lio_23xx_nic what ough to be the one for my card, but considering it has __'nic'__ in the name i suppose it's for `fw_type=nic`.

i also didn't see any hint that you're building the OVS offload version here. So, really, could you give me a hint as to how this ovs offload version came about?
(I found a 2017 presentation that described the port etc)

**Comment by chaudron** [comment]
I do not have any Marvell cards to try, but you should check with their support. 

OVS will have TC hardware offload compiled in by default you just need to enable it in the configuration.

**Comment by FlorianHeigl** [comment]
@chaudron thank you for the reply. I'll try my luck with support, and also make a OVS test build so I can find the config knob. It's great to know I have some options if the path via support doesn't work out. So really thanks that you took the moment to answer.

**Comment by FlorianHeigl** [comment]
for anyone else finding this - if you, magically, had managed to obtain the firmware, and then were to try this you'd fail, because you'll need to undo this commit: https://mails.dpdk.org/archives/dev/2023-April/267423.html
(But if you managed to get any response from Marvell, then that is a comparably tiny issue)

I had forgotten I had already tried this stuff so I'll forget about it once more.
